server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO
  loggers:
    deprecation: ERROR
    org.hibernate: ERROR
    QueuedSender: WARN
  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

shards:
  shards:
    - driverClass: org.mariadb.jdbc.Driver
      user: root
      password: root
      url: jdbc:mariadb://127.0.0.1/statesman_shard1?createDatabaseIfNotExist=true
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MariaDBDialect
        hibernate.hbm2ddl.auto: update
        hibernate.show_sql: true
      maxWaitForConnection: 1s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 8
      initialSize: 8
      checkConnectionWhileIdle: false

    - driverClass: org.mariadb.jdbc.Driver
      user: root
      password: root
      url: jdbc:mariadb://127.0.0.1/statesman_shard2?createDatabaseIfNotExist=true
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MariaDBDialect
        hibernate.hbm2ddl.auto: update
        hibernate.show_sql: true
      maxWaitForConnection: 1s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 8
      initialSize: 8
      checkConnectionWhileIdle: false

swagger:
  resourcePackage: io.appform.statesman.server.resources
  title: Statesman
  description: Statesman Backend



httpActionDefaultConfig:
  connections: 10
  idleTimeOutSeconds: 30
  connectTimeoutMs: 10000
  opTimeoutMs: 10000

eventPublisherConfig:
  httpClientConfiguration:
    connections: 10
    idleTimeOutSeconds: 30
    connectTimeoutMs: 10000
    opTimeoutMs: 10000
  endpoint: "http://34.93.41.24/sendBulkMsg"
  batchSize: 50
  queuePath: /tmp/statesman


ivrDropDetection:
  enabled: true
  detectionPatterns:
    ozonetel_punjab:
      - "payload.*"
